name: Build old docker images

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

env:
  DOCKER_IMAGE: brammys/necesse-server

jobs:
  build:
    name: ${{ env.DOCKER_IMAGE }}:${{matrix.version}}
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - version: 0-21-27
            build: 10229868
            url: https://necessegame.com/wp-content/uploads/2022/12/necesse-server-linux64-0-21-27-10229868.zip
          - version: 0-21-26
            build: 9973476
            url: https://necessegame.com/wp-content/uploads/2022/11/necesse-server-linux64-0-21-26-9973476.zip
          - version: 0-21-25
            build: 9650339
            url: https://necessegame.com/wp-content/uploads/2022/10/necesse-server-linux64-0-21-25-9650339.zip
          - version: 0-21-24
            build: 9363221
            url: https://necessegame.com/wp-content/uploads/2022/08/necesse-server-linux64-0-21-24-9363221.zip
          - version: 0-21-23
            build: 9096788
            url: https://necessegame.com/wp-content/uploads/2022/07/necesse-server-linux64-0-21-23-9096788.zip
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build image
        run: docker build --build-arg url=${{matrix.url}} --build-arg version=${{matrix.version}} --build-arg build=${{matrix.build}} -t ${{ env.DOCKER_IMAGE }}:${{matrix.version}} -f ./Dockerfile .
        
      - name: Publish image
        run: docker push ${{ env.DOCKER_IMAGE }}:${{matrix.version}}
