name: Build docker images

on:
  push:
    paths:
      - 'Dockerfile'
      - 'cfg/server.cfg'
      - 'cfg/worldSettings.cfg'
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - version: 0-21-25
            build: 9593077
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - run: echo ${{matrix.os}}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build image
        run: docker build --build-arg version=${{matrix.version}} --build-arg build=${{matrix.build}} -t brammys/necesse-server:${{matrix.version}} -f ./Dockerfile .
        
      - name: Publish image
        run: docker push brammys/necesse-server:${{matrix.version}}

      - name: Tag latest image
        run: docker tag brammys/necesse-server:${{matrix.version}} brammys/necesse-server:latest
        
      - name: Publish latest image
        run: docker push brammys/necesse-server:latest
